---
# tasks file for db


- name: Add mysql yum repository
  yum:
    name: https://dev.mysql.com/get/mysql80-community-release-el7-1.noarch.rpm
    state: present


- name: Install mysql server
  yum:
    name: mysql-server
    state: present


- name: Start mysql service
  systemd:
    name: mysqld
    state: started
